name: Build and Test

on:
  push:
    branches: 
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['1.21', '1.22']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Build binary
        run: go build -v ./...

  cross-compile:
    name: Cross Compile Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test cross compilation
        run: |
          # Test compilation for different platforms
          echo "Testing cross-compilation for multiple platforms..."
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -o /tmp/test-windows-amd64.exe
          GOOS=windows GOARCH=386 go build -o /tmp/test-windows-386.exe
          GOOS=windows GOARCH=arm64 go build -o /tmp/test-windows-arm64.exe
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -o /tmp/test-linux-amd64
          GOOS=linux GOARCH=386 go build -o /tmp/test-linux-386
          GOOS=linux GOARCH=arm go build -o /tmp/test-linux-arm
          GOOS=linux GOARCH=arm64 go build -o /tmp/test-linux-arm64
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -o /tmp/test-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o /tmp/test-darwin-arm64
          
          # FreeBSD
          GOOS=freebsd GOARCH=amd64 go build -o /tmp/test-freebsd-amd64
          GOOS=freebsd GOARCH=386 go build -o /tmp/test-freebsd-386
          GOOS=freebsd GOARCH=arm64 go build -o /tmp/test-freebsd-arm64
          
          # OpenBSD
          GOOS=openbsd GOARCH=amd64 go build -o /tmp/test-openbsd-amd64
          GOOS=openbsd GOARCH=386 go build -o /tmp/test-openbsd-386
          
          # NetBSD
          GOOS=netbsd GOARCH=amd64 go build -o /tmp/test-netbsd-amd64
          GOOS=netbsd GOARCH=386 go build -o /tmp/test-netbsd-386
          
          echo "✅ All cross-compilation tests passed!"